function SetFont(typeface, fontsize)
    % Set typeface and font size for all defaults. 
    % SetFont(typeface [string], fontsize [int])
    % SetFont('Arial', 16)
    % This function can be run as a standalone or called at the beginning of a figure
    % generation script to ensure that all font elements are consistent. Especially useful
    % when changing elements for a poster or paper.
    
    % Default values
    if exist('typeface', 'var') == 0
        typeface = 'Arial';
    elseif ischar(typeface) == 0
        error('Given "typeface" is not a string')
    else
        font_list = listfonts;
        if ~any(strcmp(font_list, typeface))
           warning(['Desired typeface is not found in system list. ',...
                    'Check if installed correctly (for all users) but note that it may load anyway. ', ...
                    'Use "listfonts" to view typefaces available to Matlab'])
        end
    end

    if exist('fontsize', 'var') == 0
        fontsize = 12;
    elseif isnumeric(fontsize)
        if round(fontsize) ~= fontsize
            error('Fontsize must be an integer')
        end
    else
        error('Given "fontsize" is not numerical')
    end
    
    % Override defaults
    set(0,'DefaultFigureWindowStyle','normal',...
          'DefaultAxesFontName',typeface,...
          'DefaultAxesFontSize', fontsize, ...
          'DefaultAxesFontAngle', 'normal', ...
          'DefaultAxesFontWeight', 'normal', ...
          'DefaultAxesFontSizeMode', 'manual', ...
          'DefaultAxesLabelFontSizeMultiplier', 1,...
          'DefaultAxesTitleFontWeight', 'bold', ...
          'DefaultAxesTitleFontSizeMultiplier', 1,...
          'DefaultAxesLineWidth', 1,...
          'FixedWidthFontName',typeface,...
          'DefaultTextFontName',typeface,...
          'DefaultAxesFontSize', fontsize, ...
          'DefaultTextboxshapeFontName',typeface,...
          'DefaultTextboxshapeFontSize', fontsize, ...
          'DefaultTextarrowshapeFontName',typeface,...
          'DefaultTextarrowshapeFontSize', fontsize, ...
          'DefaultPolaraxesFontName',typeface,...
          'DefaultPolaraxesFontSize', fontsize, ...
          'DefaultLegendFontName',typeface,...
          'DefaultLegendFontSize', fontsize, ...
          'DefaultColorbarFontName',typeface,...
          'DefaultColorbarFontSize', fontsize, ...
          'DefaultTextFontSize', fontsize,...
          'defaultfigurecolor', 'w');
end