function SetFont(typeface, fontsize)
    % Set typeface and font size for all defaults. 
    % SetFont(typeface [string], fontsize [int])
    % This function can be run as a standalone or called at the beginning of a figure
    % generation script to ensure that all font elements are consistent. Especially useful
    % when changing elements for a poster or paper.

    set(0,'DefaultFigureWindowStyle','normal',...
          'DefaultAxesFontName',typeface,...
          'DefaultAxesFontSize', fontsize, ...
          'DefaultAxesFontAngle', 'normal', ...
          'DefaultAxesFontWeight', 'normal', ...
          'DefaultAxesFontSizeMode', 'manual', ...
          'DefaultAxesLabelFontSizeMultiplier', 1,...
          'DefaultAxesTitleFontWeight', 'bold', ...
          'DefaultAxesTitleFontSizeMultiplier', 1,...
          'DefaultAxesLineWidth', 1,...
          'FixedWidthFontName',typeface,...
          'DefaultTextFontName',typeface,...
          'DefaultAxesFontSize', fontsize, ...
          'DefaultTextboxshapeFontName',typeface,...
          'DefaultTextboxshapeFontSize', fontsize, ...
          'DefaultTextarrowshapeFontName',typeface,...
          'DefaultTextarrowshapeFontSize', fontsize, ...
          'DefaultPolaraxesFontName',typeface,...
          'DefaultPolaraxesFontSize', fontsize, ...
          'DefaultLegendFontName',typeface,...
          'DefaultLegendFontSize', fontsize, ...
          'DefaultColorbarFontName',typeface,...
          'DefaultColorbarFontSize', fontsize, ...
          'DefaultTextFontSize', fontsize,...
          'defaultfigurecolor', 'w');
end