function SetFont(typeface, fontsize)
    % Set typeface and font size for all defaults. 
    % SetFont(typeface [char], fontsize [int])
    % SetFont('Arial', 16)
    % This function can be run as a standalone or called at the beginning of a figure
    % generation script to ensure that all font elements are consistent. Especially useful
    % when changing elements for a poster or paper.
    % Also sets the figure background color to white
    arguments
        typeface {mustBeText} = 'Arial'
        fontsize {mustBeInteger} = 12
    end
    
    % Default values
    font_list = listfonts;
    if ~any(strcmp(font_list, typeface))
       warning(['Desired typeface is not found in system list. ',...
                'Check if installed correctly (for all users) but note that it may load anyway. ', ...
                'Use "listfonts" to view typefaces available to Matlab'])
    end
    
    % Scale linewidth by fontsize
    if fontsize < 15
        line_size = 1;
    else
        line_size = round(fontsize / 10);
    end
    
    % Override defaults
    set(0,'DefaultFigureWindowStyle','normal',...
          'DefaultAxesFontName',typeface,...
          'DefaultAxesFontSize', fontsize, ...
          'DefaultAxesFontAngle', 'normal', ...
          'DefaultAxesFontWeight', 'normal', ...
          'DefaultAxesFontSizeMode', 'manual', ...
          'DefaultAxesLabelFontSizeMultiplier', 1,...
          'DefaultAxesTitleFontWeight', 'bold', ...
          'DefaultAxesTitleFontSizeMultiplier', 1,...
          'DefaultAxesLineWidth', line_size,...
          'DefaultLineLineWidth', line_size,...
          'FixedWidthFontName',typeface,...
          'DefaultTextFontName',typeface,...
          'DefaultAxesFontSize', fontsize, ...
          'DefaultTextboxshapeFontName',typeface,...
          'DefaultTextboxshapeFontSize', fontsize, ...
          'DefaultTextarrowshapeFontName',typeface,...
          'DefaultTextarrowshapeFontSize', fontsize, ...
          'DefaultPolaraxesFontName',typeface,...
          'DefaultPolaraxesFontSize', fontsize, ...
          'DefaultLegendFontName',typeface,...
          'DefaultLegendFontSize', fontsize, ...
          'DefaultColorbarFontName',typeface,...
          'DefaultColorbarFontSize', fontsize, ...
          'DefaultTextFontSize', fontsize,...
          'DefaultScatterMarkerFaceAlpha', .5,...
          'DefaultPatchFaceAlpha', .5,...
          'defaultfigurecolor', 'w');
end